export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SCREEN_SETTING = 'SCREEN_SETTING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
